services:
  - type: web
    name: project-accounting-system
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py create_default_superuser
    startCommand: gunicorn construction_dispatch.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: project-accounting-system.onrender.com
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_PASSWORD
        value: admin123
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DATABASE_URL
        fromDatabase:
          name: project-accounting-db
          property: connectionString
    autoDeploy: true

databases:
  - name: project-accounting-db
    databaseName: project_accounting
    user: project_accounting_user
